import { type ReactNode } from "react";
import { Navigate } from "react-router-dom";
import { useQuery } from "convex/react";
import { useAuth } from "@clerk/clerk-react";
// @ts-expect-error - Generated by Convex
import { api } from "../../convex/_generated/api";

type Role = "ADMIN" | "MANAGER" | "OPERATOR";

interface RequireRoleProps {
  children: ReactNode;
  allowedRoles: Role[];
  fallback?: ReactNode;
}

export function RequireRole({ children, allowedRoles, fallback }: RequireRoleProps) {
  const { userId } = useAuth();
  const user = useQuery(api.auth.getUserByClerkId, userId ? { clerkId: userId } : "skip");
  
  // Loading state
  if (user === undefined) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-green-600"></div>
      </div>
    );
  }
  
  // Not authenticated
  if (!user) {
    return <Navigate to="/login" replace />;
  }
  
  // Check role permission
  if (!allowedRoles.includes(user.role)) {
    return fallback ? <>{fallback}</> : <Navigate to="/unauthorized" replace />;
  }
  
  return <>{children}</>;
}

// Hook to check if user has role
export function useHasRole(requiredRoles: Role[]): boolean | undefined {
  const { userId } = useAuth();
  const user = useQuery(api.auth.getUserByClerkId, userId ? { clerkId: userId } : "skip");
  
  if (user === undefined) return undefined; // Loading
  if (!user) return false; // Not authenticated
  
  return requiredRoles.includes(user.role);
}

// Hook to get current user with role
export function useCurrentUser() {
  const { userId } = useAuth();
  return useQuery(api.auth.getUserByClerkId, userId ? { clerkId: userId } : "skip");
}

// Higher-order component for admin-only content
interface AdminOnlyProps {
  children: ReactNode;
  fallback?: ReactNode;
}

export function AdminOnly({ children, fallback = null }: AdminOnlyProps) {
  const isAdmin = useHasRole(["ADMIN"]);
  
  if (isAdmin === undefined) return null; // Loading
  if (!isAdmin) return <>{fallback}</>;
  
  return <>{children}</>;
}

// Higher-order component for manager+ content
export function ManagerOnly({ children, fallback = null }: AdminOnlyProps) {
  const isManager = useHasRole(["ADMIN", "MANAGER"]);
  
  if (isManager === undefined) return null; // Loading
  if (!isManager) return <>{fallback}</>;
  
  return <>{children}</>;
}
