/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

// Temporary type definitions until npx convex dev is run
export * from "convex/server";

// These will be properly generated by Convex
import type { 
  GenericMutationCtx,
  GenericQueryCtx,
  GenericActionCtx,
} from "convex/server";

export type MutationCtx = GenericMutationCtx<any>;
export type QueryCtx = GenericQueryCtx<any>;
export type ActionCtx = GenericActionCtx<any>;

