import { useState, useEffect } from "react";
import { NavLink, Outlet, useNavigate, useLocation } from "react-router-dom";
import {
  LayoutDashboard, Warehouse, Sprout, FlaskConical,
  GitMerge, BrainCircuit, ClipboardList, FileBarChart2,
  Menu, X, LogOut, ChevronRight, Leaf, Sun, Moon, Keyboard,
  PanelLeftClose, PanelLeft,
} from "lucide-react";
import { useClerk, useUser } from "@clerk/clerk-react";
import { useQuery } from "convex/react";
// @ts-expect-error - Generated by Convex
import { api } from "../../convex/_generated/api";
import { useData } from "../contexts/ConvexDataContext";
import { useTheme } from "../contexts/ThemeContext";
import { useToast } from "../components/Toast";
import { OrganizationSelector } from "../components/OrganizationSelector";
import NotificationPanel from "../components/ConvexNotificationPanel";
import { useGlobalKeyboardShortcuts, SkipNavLink, AriaLiveRegions, KeyboardShortcutsHelp } from "../hooks/useAccessibility";

const NAV = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard, section: "Overview" },
  { to: "/warehouses", label: "Warehouses", icon: Warehouse, section: "Operations" },
  { to: "/crops", label: "Crops", icon: Sprout, section: "Operations" },
  { to: "/resources", label: "Resources", icon: FlaskConical, section: "Operations" },
  { to: "/allocations", label: "Allocations", icon: GitMerge, section: "Operations" },
  { to: "/ai-insights", label: "AI Insights", icon: BrainCircuit, section: "Intelligence" },
  { to: "/audit-log", label: "Audit Log", icon: ClipboardList, section: "Intelligence" },
  { to: "/reports", label: "Reports", icon: FileBarChart2, section: "Intelligence" },
];

const SECTIONS = ["Overview", "Operations", "Intelligence"] as const;

const ROLE_STYLES: Record<string, { bg: string; text: string; dot: string }> = {
  ADMIN: { bg: "bg-rose-500/10", text: "text-rose-600 dark:text-rose-400", dot: "bg-rose-500" },
  MANAGER: { bg: "bg-blue-500/10", text: "text-blue-600 dark:text-blue-400", dot: "bg-blue-500" },
  OPERATOR: { bg: "bg-emerald-500/10", text: "text-emerald-600 dark:text-emerald-400", dot: "bg-emerald-500" },
};

export default function MainLayout() {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [shortcutsOpen, setShortcutsOpen] = useState(false);
  const { user } = useUser();
  const { signOut } = useClerk();
  const { organizationName } = useData();
  const { theme, toggleTheme } = useTheme();
  const { addToast } = useToast();
  const navigate = useNavigate();
  const location = useLocation();
  
  const currentUser = useQuery(api.auth.getCurrentUser);

  useGlobalKeyboardShortcuts({
    navigate_dashboard: () => navigate("/"),
    navigate_warehouses: () => navigate("/warehouses"),
    navigate_crops: () => navigate("/crops"),
    navigate_resources: () => navigate("/resources"),
    navigate_allocations: () => navigate("/allocations"),
    navigate_ai_insights: () => navigate("/ai-insights"),
    navigate_audit_log: () => navigate("/audit-log"),
    navigate_reports: () => navigate("/reports"),
    show_shortcuts: () => setShortcutsOpen(true),
  });

  const pathname = location.pathname;
  useEffect(() => {
    if (mobileOpen) {
      const timer = requestAnimationFrame(() => setMobileOpen(false));
      return () => cancelAnimationFrame(timer);
    }
  }, [pathname]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    const handler = () => {
      if (window.innerWidth >= 768) setMobileOpen(false);
    };
    window.addEventListener("resize", handler);
    return () => window.removeEventListener("resize", handler);
  }, []);

  async function handleLogout() {
    await signOut();
    addToast("Logged out successfully", "info");
    navigate("/login");
  }

  const currentPage =
    location.pathname === "/"
      ? "Dashboard"
      : location.pathname.slice(1).replace(/-/g, " ").split("/")[0];
  
  const userName = user?.fullName || user?.primaryEmailAddress?.emailAddress || "User";
  const userInitial = userName.charAt(0).toUpperCase();
  const userRole = currentUser?.role || "OPERATOR";
  const roleStyle = ROLE_STYLES[userRole] || ROLE_STYLES.OPERATOR;

  const sidebarContent = (isDesktop: boolean) => {
    const expanded = isDesktop ? sidebarOpen : true;
    return (
      <>
        {/* Logo */}
        <div className="flex items-center gap-3 px-5 py-5 min-h-[68px]">
          <div className="relative flex-shrink-0">
            <div className="w-9 h-9 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-xl flex items-center justify-center shadow-md shadow-emerald-500/20">
              <Leaf size={18} className="text-white" />
            </div>
            <div className="absolute -bottom-0.5 -right-0.5 w-2.5 h-2.5 bg-emerald-400 rounded-full border-2 border-[var(--surface)]" />
          </div>
          {expanded && (
            <div className="overflow-hidden animate-fade-in">
              <p className="font-display font-bold text-[var(--text-primary)] text-sm tracking-tight leading-none">AgroTech</p>
              <p className="text-[11px] text-[var(--text-muted)] mt-1 truncate max-w-[140px]">{organizationName || "No Organization"}</p>
            </div>
          )}
          {!isDesktop && (
            <button
              onClick={() => setMobileOpen(false)}
              className="ml-auto p-1.5 rounded-lg hover:bg-[var(--surface-hover)] text-[var(--text-muted)] md:hidden transition-colors"
            >
              <X size={18} />
            </button>
          )}
        </div>

        {/* Divider */}
        <div className="mx-4 border-t border-[var(--border)]" />

        {/* Nav */}
        <nav className="flex-1 py-4 overflow-y-auto">
          {SECTIONS.map((section) => {
            const items = NAV.filter((n) => n.section === section);
            if (items.length === 0) return null;
            return (
              <div key={section} className="mb-2">
                {expanded && (
                  <p className="px-5 py-1.5 text-[10px] font-semibold uppercase tracking-[0.08em] text-[var(--text-muted)]">
                    {section}
                  </p>
                )}
                <div className="space-y-0.5">
                  {items.map(({ to, label, icon: Icon }) => (
                    <NavLink
                      key={to}
                      to={to}
                      end={to === "/"}
                      className={({ isActive }) =>
                        `sidebar-nav-item ${isActive ? "active" : ""} ${!expanded ? "justify-center mx-1 px-0" : ""}`
                      }
                      title={!expanded ? label : undefined}
                    >
                      <Icon size={18} className="flex-shrink-0" />
                      {expanded && <span className="truncate">{label}</span>}
                    </NavLink>
                  ))}
                </div>
              </div>
            );
          })}
        </nav>

        {/* Footer */}
        <div className="border-t border-[var(--border)] p-4 space-y-3">
          {/* Theme toggle */}
          {expanded ? (
            <button
              onClick={toggleTheme}
              className="flex items-center gap-2.5 w-full px-2 py-2 text-sm text-[var(--text-muted)] hover:text-[var(--text-primary)] rounded-xl hover:bg-[var(--surface-hover)] transition-all group"
            >
              <div className="w-8 h-8 rounded-lg bg-[var(--surface-hover)] group-hover:bg-[var(--surface)] flex items-center justify-center transition-colors">
                {theme === "dark" ? <Sun size={14} /> : <Moon size={14} />}
              </div>
              <span className="text-[13px]">{theme === "dark" ? "Light Mode" : "Dark Mode"}</span>
            </button>
          ) : (
            <button
              onClick={toggleTheme}
              className="w-full flex justify-center p-2 text-[var(--text-muted)] hover:text-[var(--text-primary)] rounded-lg hover:bg-[var(--surface-hover)] transition-all"
            >
              {theme === "dark" ? <Sun size={16} /> : <Moon size={16} />}
            </button>
          )}

          {/* User */}
          {expanded ? (
            <div className="flex items-center gap-3 px-2 py-2 rounded-xl bg-[var(--surface-hover)]">
              <div className="w-9 h-9 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-xl flex items-center justify-center flex-shrink-0 shadow-sm">
                <span className="text-white text-xs font-bold">{userInitial}</span>
              </div>
              <div className="overflow-hidden flex-1 min-w-0">
                <p className="text-sm font-medium text-[var(--text-primary)] truncate">{userName}</p>
                <div className="flex items-center gap-1.5 mt-0.5">
                  <div className={`w-1.5 h-1.5 rounded-full ${roleStyle.dot}`} />
                  <span className={`text-[11px] font-medium ${roleStyle.text}`}>{userRole}</span>
                </div>
              </div>
            </div>
          ) : (
            <div className="flex justify-center">
              <div className="w-9 h-9 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-xl flex items-center justify-center shadow-sm" title={userName}>
                <span className="text-white text-xs font-bold">{userInitial}</span>
              </div>
            </div>
          )}

          {expanded && (
            <button
              onClick={handleLogout}
              className="flex items-center gap-2.5 w-full px-2 py-1.5 text-sm text-[var(--text-muted)] hover:text-rose-600 dark:hover:text-rose-400 rounded-lg hover:bg-rose-50 dark:hover:bg-rose-500/10 transition-all"
            >
              <LogOut size={15} />
              <span className="text-[13px]">Sign Out</span>
            </button>
          )}
        </div>
      </>
    );
  };

  return (
    <div className="flex h-screen overflow-hidden" style={{ background: "var(--bg-primary)" }}>
      <SkipNavLink />
      <AriaLiveRegions />

      {/* Keyboard Shortcuts Modal */}
      {shortcutsOpen && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center animate-fade-in" onClick={() => setShortcutsOpen(false)}>
          <div className="fixed inset-0 bg-black/40 backdrop-blur-sm" />
          <div className="relative card p-6 max-w-lg w-full mx-4 max-h-[80vh] overflow-y-auto animate-scale-in" onClick={(e) => e.stopPropagation()}>
            <KeyboardShortcutsHelp onClose={() => setShortcutsOpen(false)} />
          </div>
        </div>
      )}

      {/* Mobile backdrop */}
      {mobileOpen && (
        <div
          className="fixed inset-0 bg-black/30 backdrop-blur-sm z-40 md:hidden animate-fade-in"
          onClick={() => setMobileOpen(false)}
        />
      )}

      {/* Mobile sidebar */}
      <aside
        className={`fixed inset-y-0 left-0 z-50 w-[260px] flex flex-col transform transition-transform duration-300 md:hidden`}
        style={{ background: "var(--surface)", borderRight: "1px solid var(--border)", transform: mobileOpen ? "translateX(0)" : "translateX(-100%)" }}
      >
        {sidebarContent(false)}
      </aside>

      {/* Desktop sidebar */}
      <aside
        className="hidden md:flex flex-col flex-shrink-0 transition-all duration-300 ease-out"
        style={{
          background: "var(--surface)",
          borderRight: "1px solid var(--border)",
          width: sidebarOpen ? "260px" : "72px",
        }}
      >
        {sidebarContent(true)}
      </aside>

      {/* Main content */}
      <div className="flex flex-col flex-1 min-w-0">
        {/* Topbar */}
        <header
          className="glass flex items-center gap-3 px-5 py-3 min-h-[64px] z-10"
          style={{ borderBottom: "1px solid var(--border)" }}
        >
          {/* Mobile hamburger */}
          <button
            onClick={() => setMobileOpen(true)}
            className="p-2 rounded-lg hover:bg-[var(--surface-hover)] text-[var(--text-muted)] md:hidden transition-colors"
          >
            <Menu size={20} />
          </button>

          {/* Desktop sidebar toggle */}
          <button
            onClick={() => setSidebarOpen((v) => !v)}
            className="p-2 rounded-lg hover:bg-[var(--surface-hover)] text-[var(--text-muted)] hidden md:flex items-center justify-center transition-colors"
            title={sidebarOpen ? "Collapse sidebar" : "Expand sidebar"}
          >
            {sidebarOpen ? <PanelLeftClose size={18} /> : <PanelLeft size={18} />}
          </button>

          {/* Breadcrumb */}
          <div className="flex items-center gap-1.5 text-sm">
            <span className="text-[var(--brand-600)] dark:text-[var(--brand-400)] font-medium font-display">AgroTech</span>
            <ChevronRight size={14} className="text-[var(--text-muted)]" />
            <span className="text-[var(--text-primary)] font-semibold capitalize font-display">
              {currentPage}
            </span>
          </div>

          {/* Right actions */}
          <div className="ml-auto flex items-center gap-1.5">
            <button
              onClick={() => setShortcutsOpen(true)}
              className="p-2 rounded-lg hover:bg-[var(--surface-hover)] text-[var(--text-muted)] hidden md:flex items-center justify-center transition-colors"
              title="Keyboard shortcuts (?)"
            >
              <Keyboard size={16} />
            </button>
            <NotificationPanel />
            <div className="hidden md:block">
              <OrganizationSelector />
            </div>
          </div>

          {/* Mobile dark mode toggle */}
          <button
            onClick={toggleTheme}
            className="p-2 rounded-lg hover:bg-[var(--surface-hover)] text-[var(--text-muted)] md:hidden transition-colors"
          >
            {theme === "dark" ? <Sun size={18} /> : <Moon size={18} />}
          </button>
        </header>

        {/* Page content */}
        <main id="main-content" className="flex-1 overflow-y-auto p-5 md:p-7">
          <div className="page-enter">
            <Outlet />
          </div>
        </main>
      </div>
    </div>
  );
}
