// Example: Admin-only page using RequireRole

import { RequireRole } from "../components/RequireRole";
import { useQuery, useMutation } from "convex/react";
// @ts-expect-error - Generated by Convex
import { api } from "../../convex/_generated/api";

export default function AdminUsersPage() {
  return (
    <RequireRole allowedRoles={["ADMIN"]}>
      <AdminUsersContent />
    </RequireRole>
  );
}

function AdminUsersContent() {
  const users = useQuery(api.users.listUsers, { organizationId: "org_id" });
  const deleteUser = useMutation(api.users.deleteUser);
  const updateRole = useMutation(api.users.updateUserRole);

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-6">User Management (Admin Only)</h1>
      
      <div className="space-y-4">
        {users?.map((user) => (
          <div key={user._id} className="p-4 bg-white rounded-lg shadow">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="font-semibold">{user.name}</h3>
                <p className="text-sm text-gray-600">{user.email}</p>
                <span className="text-xs px-2 py-1 bg-blue-100 text-blue-700 rounded">
                  {user.role}
                </span>
              </div>
              
              <div className="flex gap-2">
                <select
                  value={user.role}
                  onChange={async (e) => {
                    await updateRole({
                      userId: user._id,
                      role: e.target.value as "ADMIN" | "MANAGER" | "OPERATOR",
                    });
                  }}
                  className="px-3 py-1 border rounded"
                >
                  <option value="OPERATOR">Operator</option>
                  <option value="MANAGER">Manager</option>
                  <option value="ADMIN">Admin</option>
                </select>
                
                <button
                  onClick={async () => {
                    if (confirm("Delete user?")) {
                      await deleteUser({ userId: user._id });
                    }
                  }}
                  className="px-3 py-1 bg-red-600 text-white rounded hover:bg-red-700"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
