import { useState } from "react";
import { useQuery } from "convex/react";
// @ts-expect-error - Generated by Convex
import { api } from "../../convex/_generated/api";
import { useOrganization } from "../contexts/OrganizationContext";
import {
    FileBarChart2, Download, Calendar, Warehouse,
    GitMerge, FlaskConical, TrendingUp, TrendingDown, AlertCircle, FileText,
} from "lucide-react";
import {
    BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer,
    CartesianGrid, Cell, LineChart, Line, Legend, PieChart, Pie,
} from "recharts";
import { useToast } from "../components/Toast";
import {
    exportWarehouseReportPDF,
    exportAllocationReportPDF,
    exportResourceReportPDF,
    exportCropReportPDF,
    exportDashboardSummaryPDF,
} from "../utils/pdfExport";

type Tab = "dashboard" | "warehouse" | "allocation" | "resource" | "crop";
type GroupBy = "crop" | "warehouse" | "date";

const COLORS = ["#3b82f6", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6", "#ec4899"];

function toCSV(headers: string[], rows: string[][]) {
    const escape = (s: string) => `"${s.replace(/"/g, '""')}"`;
    const lines = [headers.map(escape).join(","), ...rows.map((r) => r.map(escape).join(","))];
    return lines.join("\n");
}

function downloadCSV(filename: string, csv: string) {
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

export default function ReportsPage() {
    const { selectedOrganization } = useOrganization();
    const { addToast } = useToast();
    const [tab, setTab] = useState<Tab>("dashboard");
    const [groupBy, setGroupBy] = useState<GroupBy>("crop");

    // Date range — default last 90 days
    const [startDate, setStartDate] = useState(() => {
        const d = new Date(Date.now() - 90 * 86400000);
        return d.toISOString().slice(0, 10);
    });
    const [endDate, setEndDate] = useState(() => new Date().toISOString().slice(0, 10));

    const startTs = new Date(startDate).getTime();
    const endTs = new Date(endDate).getTime() + 86400000; // inclusive end

    // Query Convex reports
    const warehouseReport = useQuery(
        api.reports.getWarehouseReport,
        tab === "warehouse" && selectedOrganization
            ? { organizationId: selectedOrganization._id, startDate: startTs, endDate: endTs }
            : "skip"
    );

    const allocationReport = useQuery(
        api.reports.getAllocationReport,
        tab === "allocation" && selectedOrganization
            ? { organizationId: selectedOrganization._id, groupBy, startDate: startTs, endDate: endTs }
            : "skip"
    );

    const resourceReport = useQuery(
        api.reports.getResourceUsageReport,
        tab === "resource" && selectedOrganization
            ? { organizationId: selectedOrganization._id, startDate: startTs, endDate: endTs }
            : "skip"
    );

    const cropReport = useQuery(
        api.reports.getCropReport,
        tab === "crop" && selectedOrganization
            ? { organizationId: selectedOrganization._id, startDate: startTs, endDate: endTs }
            : "skip"
    );

    const dashboardSummary = useQuery(
        api.reports.getDashboardSummary,
        tab === "dashboard" && selectedOrganization
            ? { organizationId: selectedOrganization._id }
            : "skip"
    );

    // Export handlers
    function handleExport() {
        if (tab === "warehouse" && warehouseReport) {
            const csv = toCSV(
                ["Name", "Location", "Total Capacity", "Used Capacity", "Utilization %", "Status", "Allocations"],
                warehouseReport.warehouses.map((w: any) => [
                    w.name, w.location, String(w.totalCapacity), String(w.usedCapacity),
                    `${w.utilizationPercent}%`, w.status, String(w.totalAllocations)
                ])
            );
            downloadCSV("warehouse_report.csv", csv);
        } else if (tab === "allocation" && allocationReport) {
            const csv = toCSV(
                ["Group", "Count", "Total Quantity", "Avg Quantity"],
                allocationReport.allocations.map((a: any) => [
                    a.groupKey, String(a.count), String(a.totalQuantity), String(a.avgQuantity)
                ])
            );
            downloadCSV("allocation_report.csv", csv);
        } else if (tab === "resource" && resourceReport) {
            const csv = toCSV(
                ["Name", "Type", "Stock", "Used", "Avg Daily", "Days Until Depletion"],
                resourceReport.resources.map((r: any) => [
                    r.name, r.type, String(r.currentStock), String(r.totalUsed),
                    String(r.avgDailyUsage), r.daysUntilDepletion !== null ? String(r.daysUntilDepletion) : "N/A"
                ])
            );
            downloadCSV("resource_usage_report.csv", csv);
        } else if (tab === "crop" && cropReport) {
            const csv = toCSV(
                ["Name", "Status", "Quantity", "Allocations", "Allocation Rate %", "Resources"],
                cropReport.crops.map((c: any) => [
                    c.name, c.status, String(c.totalQuantity), String(c.allocationCount),
                    String(c.allocationRate), String(c.resourceCount)
                ])
            );
            downloadCSV("crop_report.csv", csv);
        } else if (tab === "dashboard" && dashboardSummary) {
            const csv = toCSV(
                ["Metric", "Value"],
                [
                    ["Total Warehouses", String(dashboardSummary.summary.totalWarehouses)],
                    ["Total Crops", String(dashboardSummary.summary.totalCrops)],
                    ["Total Allocations", String(dashboardSummary.summary.totalAllocations)],
                    ["Avg Utilization %", String(dashboardSummary.summary.avgUtilization)],
                ]
            );
            downloadCSV("dashboard_summary.csv", csv);
        }
    }

    function handleExportPDF() {
        const orgName = selectedOrganization?.name || "Unknown";
        const range = tab !== "dashboard" ? { start: startDate, end: endDate } : undefined;
        try {
            if (tab === "warehouse" && warehouseReport) {
                exportWarehouseReportPDF(warehouseReport, orgName, range);
            } else if (tab === "allocation" && allocationReport) {
                exportAllocationReportPDF(allocationReport, orgName, groupBy, range);
            } else if (tab === "resource" && resourceReport) {
                exportResourceReportPDF(resourceReport, orgName, range);
            } else if (tab === "crop" && cropReport) {
                exportCropReportPDF(cropReport, orgName, range);
            } else if (tab === "dashboard" && dashboardSummary) {
                exportDashboardSummaryPDF(dashboardSummary, orgName);
            }
            addToast("PDF report downloaded", "success");
        } catch {
            addToast("Failed to generate PDF", "error");
        }
    }

    const tabs: { key: Tab; label: string; icon: typeof Warehouse }[] = [
        { key: "dashboard", label: "Dashboard", icon: FileBarChart2 },
        { key: "warehouse", label: "Warehouses", icon: Warehouse },
        { key: "allocation", label: "Allocations", icon: GitMerge },
        { key: "resource", label: "Resources", icon: FlaskConical },
        { key: "crop", label: "Crops", icon: TrendingUp },
    ];

    const UTIL_COLOR = (pct: number) => pct > 95 ? "#dc2626" : pct > 80 ? "#d97706" : "#16a34a";

    // Loading states
    const isLoading =
        (tab === "dashboard" && !dashboardSummary) ||
        (tab === "warehouse" && !warehouseReport) ||
        (tab === "allocation" && !allocationReport) ||
        (tab === "resource" && !resourceReport) ||
        (tab === "crop" && !cropReport);

    if (!selectedOrganization) {
        return (
            <div className="flex items-center justify-center h-64">
                <div className="text-center">
                    <AlertCircle className="text-gray-400 dark:text-gray-500 mx-auto mb-3" size={32} />
                    <p className="text-gray-500 dark:text-gray-400">Please select an organization</p>
                </div>
            </div>
        );
    }

    if (isLoading) {
        return (
            <div className="flex items-center justify-center h-64">
                <div className="text-center">
                    <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-green-600 mx-auto mb-3"></div>
                    <p className="text-gray-500 dark:text-gray-400">Loading report...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-5">
            {/* Header */}
            <div className="flex items-center justify-between flex-wrap gap-3">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
                        <FileBarChart2 className="text-green-600" size={24} /> Reports
                    </h1>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-0.5">Generate and export detailed reports</p>
                </div>
                <div className="flex items-center gap-2">
                    <button
                        onClick={handleExportPDF}
                        className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm font-medium transition-colors"
                    >
                        <FileText size={16} /> Export PDF
                    </button>
                    <button
                        onClick={handleExport}
                        className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 text-sm font-medium transition-colors"
                    >
                        <Download size={16} /> Export CSV
                    </button>
                </div>
            </div>

            {/* Tabs */}
            <div className="flex gap-1 flex-wrap">
                {tabs.map(({ key, label, icon: Icon }) => (
                    <button
                        key={key}
                        onClick={() => setTab(key)}
                        className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-colors ${tab === key
                            ? "bg-green-600 text-white"
                            : "bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700"
                            }`}
                    >
                        <Icon size={16} /> {label}
                    </button>
                ))}
            </div>

            {/* Date Range + GroupBy for Allocation */}
            {tab !== "dashboard" && (
                <div className="flex items-center justify-between flex-wrap gap-3">
                    <div className="flex items-center gap-2 text-sm">
                        <Calendar size={15} className="text-gray-400 dark:text-gray-500" />
                        <input
                            type="date"
                            value={startDate}
                            onChange={(e) => setStartDate(e.target.value)}
                            className="border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-green-500"
                        />
                        <span className="text-gray-400 dark:text-gray-500">to</span>
                        <input
                            type="date"
                            value={endDate}
                            onChange={(e) => setEndDate(e.target.value)}
                            className="border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-green-500"
                        />
                    </div>

                    {tab === "allocation" && (
                        <div className="flex items-center gap-2">
                            <span className="text-sm text-gray-600 dark:text-gray-300 font-medium">Group by:</span>
                            {(["crop", "warehouse", "date"] as GroupBy[]).map((g) => (
                                <button
                                    key={g}
                                    onClick={() => setGroupBy(g)}
                                    className={`px-3 py-1.5 text-sm font-medium rounded-lg transition-colors capitalize ${groupBy === g
                                        ? "bg-green-600 text-white"
                                        : "bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700"
                                        }`}
                                >
                                    {g}
                                </button>
                            ))}
                        </div>
                    )}
                </div>
            )}

            {/* DASHBOARD TAB */}
            {tab === "dashboard" && dashboardSummary && (
                <>
                    {/* Summary Cards */}
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm text-gray-500 dark:text-gray-400">Total Warehouses</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1">
                                        {dashboardSummary.summary.totalWarehouses}
                                    </p>
                                </div>
                                <Warehouse className="text-blue-600" size={32} />
                            </div>
                        </div>
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm text-gray-500 dark:text-gray-400">Total Crops</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1">
                                        {dashboardSummary.summary.totalCrops}
                                    </p>
                                </div>
                                <TrendingUp className="text-green-600" size={32} />
                            </div>
                        </div>
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm text-gray-500 dark:text-gray-400">Total Allocations</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1">
                                        {dashboardSummary.summary.totalAllocations}
                                    </p>
                                </div>
                                <GitMerge className="text-purple-600" size={32} />
                            </div>
                        </div>
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4">
                            <div className="flex items-center justify-between">
                                <div>
                                    <p className="text-sm text-gray-500 dark:text-gray-400">Avg Utilization</p>
                                    <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1">
                                        {dashboardSummary.summary.avgUtilization.toFixed(1)}%
                                    </p>
                                </div>
                                <FileBarChart2 className="text-orange-600" size={32} />
                            </div>
                        </div>
                    </div>

                    {/* Warehouse Utilization Chart */}
                    {dashboardSummary.warehouseUtilization && dashboardSummary.warehouseUtilization.length > 0 && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
                            <h2 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                                <Warehouse size={18} /> Warehouse Utilization
                            </h2>
                            <ResponsiveContainer width="100%" height={250}>
                                <BarChart data={dashboardSummary.warehouseUtilization} barSize={40}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6" />
                                    <XAxis dataKey="name" tick={{ fontSize: 11 }} />
                                    <YAxis tick={{ fontSize: 11 }} label={{ value: '%', position: 'insideLeft' }} />
                                    <Tooltip />
                                    <Bar dataKey="utilization" name="Utilization %" radius={[4, 4, 0, 0]}>
                                        {dashboardSummary.warehouseUtilization.map((entry: any, i: number) => (
                                            <Cell key={i} fill={UTIL_COLOR(entry.utilization)} />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    )}

                    {/* Resource Status */}
                    {dashboardSummary.resourceStatus && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
                            <h2 className="font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                                <FlaskConical size={18} /> Resource Status
                            </h2>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <div className="p-4 bg-green-50 dark:bg-green-900/30 rounded-lg border border-green-200 dark:border-green-800">
                                    <p className="text-sm text-green-700 dark:text-green-400 font-medium">In Stock</p>
                                    <p className="text-3xl font-bold text-green-900 dark:text-green-300 mt-2">
                                        {dashboardSummary.resourceStatus.inStock || 0}
                                    </p>
                                </div>
                                <div className="p-4 bg-yellow-50 dark:bg-yellow-900/30 rounded-lg border border-yellow-200 dark:border-yellow-800">
                                    <p className="text-sm text-yellow-700 dark:text-yellow-400 font-medium">Low Stock</p>
                                    <p className="text-3xl font-bold text-yellow-900 dark:text-yellow-300 mt-2">
                                        {dashboardSummary.resourceStatus.lowStock || 0}
                                    </p>
                                </div>
                                <div className="p-4 bg-red-50 dark:bg-red-900/30 rounded-lg border border-red-200 dark:border-red-800">
                                    <p className="text-sm text-red-700 dark:text-red-400 font-medium">Out of Stock</p>
                                    <p className="text-3xl font-bold text-red-900 dark:text-red-300 mt-2">
                                        {dashboardSummary.resourceStatus.outOfStock || 0}
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}
                </>
            )}

            {/* WAREHOUSE TAB */}
            {tab === "warehouse" && warehouseReport && (
                <>
                    {/* Utilization Chart */}
                    {warehouseReport.warehouses && warehouseReport.warehouses.length > 0 && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
                            <h2 className="font-semibold text-gray-900 dark:text-white mb-4">Warehouse Utilization (%)</h2>
                            <ResponsiveContainer width="100%" height={250}>
                                <BarChart data={warehouseReport.warehouses} barSize={40}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6" />
                                    <XAxis dataKey="name" tick={{ fontSize: 11 }} />
                                    <YAxis tick={{ fontSize: 11 }} />
                                    <Tooltip />
                                    <Bar dataKey="utilizationPercent" name="Utilization %" radius={[4, 4, 0, 0]}>
                                        {warehouseReport.warehouses.map((w: any, i: number) => (
                                            <Cell key={i} fill={UTIL_COLOR(w.utilizationPercent)} />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    )}

                    {/* Warehouse Table */}
                    <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-900">
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Name</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Location</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Total Capacity</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Used Capacity</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Utilization</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Status</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Allocations</th>
                                </tr>
                            </thead>
                            <tbody>
                                {!warehouseReport.warehouses || warehouseReport.warehouses.length === 0 ? (
                                    <tr><td colSpan={7} className="text-center py-10 text-gray-400 dark:text-gray-500">No warehouses found</td></tr>
                                ) : warehouseReport.warehouses.map((w: any) => (
                                    <tr key={w._id} className="border-b border-gray-50 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50">
                                        <td className="px-5 py-3 font-medium text-gray-900 dark:text-white">{w.name}</td>
                                        <td className="px-5 py-3 text-gray-500 dark:text-gray-400">{w.location}</td>
                                        <td className="px-5 py-3 dark:text-gray-300">{w.totalCapacity.toLocaleString()}</td>
                                        <td className="px-5 py-3 dark:text-gray-300">{w.usedCapacity.toLocaleString()}</td>
                                        <td className="px-5 py-3">
                                            <div className="flex items-center gap-2">
                                                <div className="w-16 bg-gray-200 dark:bg-gray-600 rounded-full h-2">
                                                    <div
                                                        className="h-2 rounded-full transition-all"
                                                        style={{ width: `${Math.min(w.utilizationPercent, 100)}%`, backgroundColor: UTIL_COLOR(w.utilizationPercent) }}
                                                    />
                                                </div>
                                                <span className="text-xs font-medium text-gray-600 dark:text-gray-300">{w.utilizationPercent}%</span>
                                            </div>
                                        </td>
                                        <td className="px-5 py-3">
                                            <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${w.status === "ACTIVE" ? "bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-400" : "bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300"
                                                }`}>
                                                {w.status}
                                            </span>
                                        </td>
                                        <td className="px-5 py-3 text-gray-600 dark:text-gray-300">{w.totalAllocations}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </>
            )}

            {/* ALLOCATION TAB */}
            {tab === "allocation" && allocationReport && (
                <>
                    {/* Trend Chart */}
                    {allocationReport.allocations && allocationReport.allocations.length > 0 && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
                            <h2 className="font-semibold text-gray-900 dark:text-white mb-4">
                                Allocation Trends (Grouped by {groupBy})
                            </h2>
                            <ResponsiveContainer width="100%" height={250}>
                                <LineChart data={allocationReport.allocations}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6" />
                                    <XAxis dataKey="groupKey" tick={{ fontSize: 11 }} />
                                    <YAxis tick={{ fontSize: 11 }} />
                                    <Tooltip />
                                    <Legend />
                                    <Line type="monotone" dataKey="totalQuantity" name="Total Quantity" stroke="#7c3aed" strokeWidth={2} />
                                    <Line type="monotone" dataKey="count" name="Count" stroke="#3b82f6" strokeWidth={2} />
                                </LineChart>
                            </ResponsiveContainer>
                        </div>
                    )}

                    {/* Allocation Table */}
                    <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-900">
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Group</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Count</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Total Quantity</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Avg Quantity</th>
                                </tr>
                            </thead>
                            <tbody>
                                {!allocationReport.allocations || allocationReport.allocations.length === 0 ? (
                                    <tr><td colSpan={4} className="text-center py-10 text-gray-400 dark:text-gray-500">No allocations in this date range</td></tr>
                                ) : allocationReport.allocations.map((a: any, idx: number) => (
                                    <tr key={idx} className="border-b border-gray-50 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50">
                                        <td className="px-5 py-3 font-medium text-gray-900 dark:text-white">{a.groupKey}</td>
                                        <td className="px-5 py-3 text-gray-600 dark:text-gray-300">{a.count}</td>
                                        <td className="px-5 py-3 dark:text-gray-300">{a.totalQuantity.toLocaleString()}</td>
                                        <td className="px-5 py-3 dark:text-gray-300">{a.avgQuantity.toFixed(2)}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </>
            )}

            {/* RESOURCE TAB */}
            {tab === "resource" && resourceReport && (
                <>
                    {/* Stock Chart */}
                    {resourceReport.resources && resourceReport.resources.length > 0 && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
                            <h2 className="font-semibold text-gray-900 dark:text-white mb-4">Resource Stock Levels</h2>
                            <ResponsiveContainer width="100%" height={250}>
                                <BarChart data={resourceReport.resources} barSize={40}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#f3f4f6" />
                                    <XAxis dataKey="name" tick={{ fontSize: 11 }} />
                                    <YAxis tick={{ fontSize: 11 }} />
                                    <Tooltip />
                                    <Bar dataKey="currentStock" name="Current Stock" radius={[4, 4, 0, 0]}>
                                        {resourceReport.resources.map((r: any, i: number) => (
                                            <Cell
                                                key={i}
                                                fill={r.currentStock === 0 ? "#dc2626" : r.currentStock < 50 ? "#d97706" : "#16a34a"}
                                            />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    )}

                    {/* Resource Table with Depletion Warnings */}
                    <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-900">
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Name</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Type</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Current Stock</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Total Used</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Avg Daily Usage</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Days Until Depletion</th>
                                </tr>
                            </thead>
                            <tbody>
                                {!resourceReport.resources || resourceReport.resources.length === 0 ? (
                                    <tr><td colSpan={6} className="text-center py-10 text-gray-400 dark:text-gray-500">No resources found</td></tr>
                                ) : resourceReport.resources.map((r: any) => (
                                    <tr key={r._id} className="border-b border-gray-50 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50">
                                        <td className="px-5 py-3 font-medium text-gray-900 dark:text-white">{r.name}</td>
                                        <td className="px-5 py-3">
                                            <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${r.type === "FERTILIZER" ? "bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-400" : "bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-400"
                                                }`}>
                                                {r.type}
                                            </span>
                                        </td>
                                        <td className="px-5 py-3 dark:text-gray-300">{r.currentStock.toLocaleString()}</td>
                                        <td className="px-5 py-3 dark:text-gray-300">{r.totalUsed.toLocaleString()}</td>
                                        <td className="px-5 py-3 dark:text-gray-300">{r.avgDailyUsage.toFixed(2)}</td>
                                        <td className="px-5 py-3">
                                            {r.daysUntilDepletion !== null ? (
                                                <div className="flex items-center gap-2">
                                                    {r.daysUntilDepletion < 7 && (
                                                        <AlertCircle className="text-red-600" size={14} />
                                                    )}
                                                    <span className={r.daysUntilDepletion < 7 ? "text-red-600 font-medium" : ""}>
                                                        {r.daysUntilDepletion} days
                                                    </span>
                                                </div>
                                            ) : (
                                                <span className="text-gray-400 dark:text-gray-500">N/A</span>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </>
            )}

            {/* CROP TAB */}
            {tab === "crop" && cropReport && (
                <>
                    {/* Distribution Pie Chart */}
                    {cropReport.crops && cropReport.crops.length > 0 && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
                            <h2 className="font-semibold text-gray-900 dark:text-white mb-4">Crop Distribution</h2>
                            <ResponsiveContainer width="100%" height={300}>
                                <PieChart>
                                    <Pie
                                        data={cropReport.crops}
                                        dataKey="totalQuantity"
                                        nameKey="name"
                                        cx="50%"
                                        cy="50%"
                                        outerRadius={100}
                                        label={({ name, value }: { name?: string; value?: number }) => `${name ?? ''}: ${value ?? 0}`}
                                    >
                                        {cropReport.crops.map((_: any, index: number) => (
                                            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                        ))}
                                    </Pie>
                                    <Tooltip />
                                    <Legend />
                                </PieChart>
                            </ResponsiveContainer>
                        </div>
                    )}

                    {/* Crop Table with Performance Metrics */}
                    <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-900">
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Name</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Status</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Total Quantity</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Allocations</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Allocation Rate</th>
                                    <th className="text-left px-5 py-3 font-medium text-gray-600 dark:text-gray-300">Resources Used</th>
                                </tr>
                            </thead>
                            <tbody>
                                {!cropReport.crops || cropReport.crops.length === 0 ? (
                                    <tr><td colSpan={6} className="text-center py-10 text-gray-400 dark:text-gray-500">No crops found</td></tr>
                                ) : cropReport.crops.map((c: any) => (
                                    <tr key={c._id} className="border-b border-gray-50 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50">
                                        <td className="px-5 py-3 font-medium text-gray-900 dark:text-white">{c.name}</td>
                                        <td className="px-5 py-3">
                                            <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${c.status === "ACTIVE" ? "bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-400" :
                                                c.status === "HARVESTING" ? "bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-400" :
                                                    "bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300"
                                                }`}>
                                                {c.status}
                                            </span>
                                        </td>
                                        <td className="px-5 py-3 dark:text-gray-300">{c.totalQuantity.toLocaleString()}</td>
                                        <td className="px-5 py-3 dark:text-gray-300">{c.allocationCount}</td>
                                        <td className="px-5 py-3">
                                            <div className="flex items-center gap-2">
                                                {c.allocationRate > 75 ? (
                                                    <TrendingUp className="text-green-600" size={14} />
                                                ) : c.allocationRate < 25 ? (
                                                    <TrendingDown className="text-red-600" size={14} />
                                                ) : null}
                                                <span>{c.allocationRate.toFixed(1)}%</span>
                                            </div>
                                        </td>
                                        <td className="px-5 py-3 text-gray-600 dark:text-gray-300">{c.resourceCount}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </>
            )}

            {/* Summary footer */}
            <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4">
                <div className="flex items-center justify-between text-sm text-gray-500 dark:text-gray-400 flex-wrap gap-2">
                    <span>
                        {tab === "dashboard" && dashboardSummary && `Dashboard Summary - ${dashboardSummary.summary.totalWarehouses} warehouses, ${dashboardSummary.summary.totalCrops} crops`}
                        {tab === "warehouse" && warehouseReport && `${warehouseReport.warehouses?.length || 0} warehouses`}
                        {tab === "allocation" && allocationReport && `${allocationReport.allocations?.length || 0} allocation groups`}
                        {tab === "resource" && resourceReport && `${resourceReport.resources?.length || 0} resources`}
                        {tab === "crop" && cropReport && `${cropReport.crops?.length || 0} crops`}
                    </span>
                    <span className="text-xs text-gray-400 dark:text-gray-500">
                        Report generated: {new Date().toLocaleString("en-IN")}
                    </span>
                </div>
            </div>
        </div>
    );
}
