import { createContext, useContext, type ReactNode } from "react";
import { useAuth, useUser } from "@clerk/clerk-react";
import { useQuery } from "convex/react";
// @ts-expect-error - This will be generated by convex dev
import { api } from "../../convex/_generated/api";

interface ConvexUser {
  _id: string;
  clerkId: string;
  email: string;
  name?: string;
  role: string;
  organizationId?: string;
}

interface AuthContextType {
  isLoading: boolean;
  isAuthenticated: boolean;
  userId: string | null;
  user: ConvexUser | null;
  userRole: string | null;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export function AuthProvider({ children }: { children: ReactNode }) {
  const { isLoaded, userId: clerkUserId, isSignedIn } = useAuth();

  // Query Convex user by Clerk ID
  const convexUser = useQuery(
    api.auth.getUserByClerkId,
    clerkUserId ? { clerkId: clerkUserId } : "skip"
  ) as ConvexUser | undefined;

  const isLoading = !isLoaded || (isSignedIn && convexUser === undefined);
  const isAuthenticated = !!(isSignedIn && convexUser);

  const value: AuthContextType = {
    isLoading,
    isAuthenticated,
    userId: convexUser?._id || null,
    user: convexUser || null,
    userRole: convexUser?.role || null,
  };

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

export function useAuthContext() {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error("useAuthContext must be used within AuthProvider");
  }
  return context;
}
