import { createContext, useContext, useState, useEffect, useRef, type ReactNode } from "react";
import { useQuery } from "convex/react";
// @ts-expect-error - Generated by Convex
import { api } from "../../convex/_generated/api";
// @ts-expect-error - Generated by Convex
import type { Id } from "../../convex/_generated/dataModel";

interface OrganizationContextType {
  currentOrgId: Id<"organizations"> | null;
  setCurrentOrgId: (id: Id<"organizations"> | null) => void;
  organizations: Array<{ _id: Id<"organizations">; name: string }> | undefined;
  isLoading: boolean;
  selectedOrganization: { _id: Id<"organizations">; name: string } | undefined;
}

const OrganizationContext = createContext<OrganizationContextType | null>(null);

export function useOrganization() {
  const ctx = useContext(OrganizationContext);
  if (!ctx) throw new Error("useOrganization must be used within OrganizationProvider");
  return ctx;
}

export function OrganizationProvider({ children }: { children: ReactNode }) {
  const [currentOrgId, setCurrentOrgId] = useState<Id<"organizations"> | null>(() => {
    // Initialize from localStorage
    const saved = localStorage.getItem("agrotech_current_org");
    return saved || null;
  });
  
  // Query all organizations
  const organizations = useQuery(api.organizations.listOrganizations);
  
  const isLoading = organizations === undefined;
  const hasInitialized = useRef(false);

  // Auto-select first organization if none selected (only once per session)
  useEffect(() => {
    if (!hasInitialized.current && !currentOrgId && organizations && organizations.length > 0) {
      hasInitialized.current = true;
      // Use setTimeout to move setState to next tick, avoiding cascading renders
      setTimeout(() => setCurrentOrgId(organizations[0]._id), 0);
    }
  }, [currentOrgId, organizations]);

  // Save to localStorage when changed
  useEffect(() => {
    if (currentOrgId) {
      localStorage.setItem("agrotech_current_org", currentOrgId);
    }
  }, [currentOrgId]);

  const selectedOrganization = organizations?.find(
    (o: { _id: Id<"organizations">; name: string }) => o._id === currentOrgId
  );

  return (
    <OrganizationContext.Provider value={{ currentOrgId, setCurrentOrgId, organizations, isLoading, selectedOrganization }}>
      {children}
    </OrganizationContext.Provider>
  );
}
